### ISSUE TITLE
freerdp problem!

### ISSUE THREAD

**Issue by kuboosoft** [UnitedRPMs/vlc#1]
I don't like delete capabilities but @region51; why you changed the path and rename the freerdp in Fedora 25? is available this update for fedora 24?

**Comment by paulcarroty** [comment]
maybe @sergiomb2 ?

**Comment by kuboosoft** [comment]
@paulcarroty no; @region51 maintains the package officially ;) I am testing some changes now... with our freerdp1 :)

**Comment by sergiomb2** [comment]
> @region51 maintains the package officially ;) 

no is it @negativo17 , try not mix up :-) 
https://admin.fedoraproject.org/pkgdb/package/rpms/freerdp/
https://apps.fedoraproject.org/packages/freerdp

**Comment by kuboosoft** [comment]
![freerdp2.pc](http://s32.postimg.org/qushkpb5x/wtf.png) :/
@sergiomb2 hocus pocus! ;)

**Comment by paulcarroty** [comment]
Merged!
