### ISSUE TITLE
vlc interface very big

### ISSUE THREAD

**Issue by ndias** [UnitedRPMs/vlc#2]
The last version of vlc the interface is very big and I can't resize it to a "normal" size, the menus are very big also, it seems I'm running vlc in 800x600

**Comment by paulcarroty** [comment]
@ndias run vlc in console and paste the output here. Screenshot and your native resolutions will be also helpful.

**Comment by paulcarroty** [comment]
@ndias I can't reproduce it: 

![screenshot from 2016-09-10 10-23-47](https://cloud.githubusercontent.com/assets/1550705/18408764/6cda9050-7741-11e6-8230-aa964bb4c8da.png)

 Delete the old configs and run vlc again:

```
$ rm -rvf ~/.config/vlc ~/.local/share/vlc
```

**Comment by ndias** [comment]
Sorry for my late reply,

This rae 2 screenshots of vlc running after removing everything of configurations of vlc
My screen resolution is 3200x1800 and vlc even after resize (second screenshot occupies half of screen in length) and the icons are very big

![screenshot from 2016-09-10 09-54-09](https://cloud.githubusercontent.com/assets/886782/18409374/5d34306a-773d-11e6-80e0-0ecd76ea7d19.png)
![screenshot from 2016-09-10 09-54-22](https://cloud.githubusercontent.com/assets/886782/18409373/5d31a8b8-773d-11e6-892c-af57bb012249.png)

**Comment by kuboosoft** [comment]
@ndias I am not sure, without a log; but you can change to GTK Interface... also your theme can affect the vlc interface...

**Comment by ndias** [comment]
That is the problem, I don't have any log or error even when run from a terminal, and switch to GTK interface doesn't solve the problem.

**Comment by ndias** [comment]
One more thing the version 3.0.0-0.5.fc24 from rpmfusion works as expected

**Comment by kuboosoft** [comment]
Vlc working without problem... F24 64 bits... with a simple "Intel Corporation 82G33/G31 Express Integrated Graphics Controller (rev 10)"...

<a href='https://postimg.org/image/lsm68h0bx/' target='_blank'><img src='https://s22.postimg.org/lsm68h0bx/test.png' border='0' alt='postimage'/></a>

**Comment by ndias** [comment]
@kuboosoft  I think this is a problem with the screen resolution, in another system with 1920x1080 I don't have any problem with vlc
