### ISSUE TITLE
chromecast support

### ISSUE THREAD

**Issue by snaggen** [UnitedRPMs/vlc#3]
It seems that chromecast support is not enabled. It would be really nice to have that enabled.

**Comment by kuboosoft** [comment]
@snaggen Can you test now?

**Comment by paulcarroty** [comment]
@kuboosoft you should use https://github.com/UnitedRPMs/travis-rpm-builder to build rpms.

**Comment by paulcarroty** [comment]
@snaggen test packages - https://github.com/UnitedRPMs/travis-rpm-builder/releases

**Comment by kuboosoft** [comment]
@paulcarroty slack ;)

**Comment by paulcarroty** [comment]
Problem still exist.

**Comment by kuboosoft** [comment]
"/usr/lib64/vlc/plugins/stream_out/libstream_out_chromecast_plugin.so"
See the comment line 456 in spec file (vlc.spec)... reading the http://unix.stackexchange.com/questions/291975/how-do-i-stream-to-chromecast-using-vlc ; "this feature is not available under the GUI..."

**Comment by snaggen** [comment]
Ok, the chromecast plugin is built and installed. So I guess the package is ok now. However, I still cant find my chromecast. According to different sources it should be available under the "Video->Renderer" entry, after you have done a "Scan"... if I understand things correctly. However, after a little googling I found a thread on reddit where people have found this to have broken a while ago... so maybe it will start working again later on....

**Comment by paulcarroty** [comment]
@snaggen "Video->Renderer" entry now seems only for windows. You should to ping VLC developers to be sure. We pushed 2-days old snapshot to repository.

**Comment by snaggen** [comment]
https://github.com/videolan/vlc/commit/d8203596f9e6a772fdaa4dd8c52ba77e49261406
This commit in VLC might have improved the situation of not being able to discover chromecast devices

**Comment by paulcarroty** [comment]
OK, thx, I'll try to compile the latest trunk.

**Comment by paulcarroty** [comment]
@snaggen please test `3.0.0-16.20161228git368f85d`.
