### ISSUE TITLE
You are experiencing problems in the installation on Fedora 29

### ISSUE THREAD

**Issue by IvanDeFelice76** [UnitedRPMs/vlc#5]
dnf install vlc

Problema: conflicting requests
  - package vlc-1:3.0.5-6.gite9d8590.fc29.x86_64 requires vlc-core = 3.0.5-6.gite9d8590.fc29, but none of the providers can be installed
  - package vlc-3.0.5-3.fc29.i686 requires libplacebo.so.6, but none of the providers can be installed
  - package vlc-core-1:3.0.5-6.gite9d8590.fc29.x86_64 requires libplacebo.so.6()(64bit), but none of the providers can be installed
  - package vlc-3.0.5-3.fc29.x86_64 requires libplacebo.so.6()(64bit), but none of the providers can be installed
  - nothing provides libshaderc_shared.so.1 needed by libplacebo-0.6.0-2.fc29.i686
  - nothing provides libshaderc_shared.so.1()(64bit) needed by libplacebo-0.6.0-2.fc29.x86_64

**Comment by kuboosoft** [comment]
Hi. Don't worry; is a issue in Fedora (missed or not sync the update) with libshaderc... the "update-testing" repository has the updated libshaderc... https://apps.fedoraproject.org/packages/shaderc

**Comment by IvanDeFelice76** [comment]
Great if it will be sorted soon thanks!!!

**Comment by sergiomb2** [comment]
so it should be solved with : 
`dnf install vlc  --enablerepo=updates-testing`

**Comment by IvanDeFelice76** [comment]
I felt like I hadn't activated something...thank you very much!!!
